-- MySQL Script generated by MySQL Workbench
-- Thu Apr  2 16:18:32 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema vuelos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vuelos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vuelos` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `vuelos` ;

-- -----------------------------------------------------
-- Table `vuelos`.`avion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos`.`avion` (
  `idAvion` INT NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(20) NOT NULL,
  `aerolinea` VARCHAR(25) NOT NULL,
  `numero_asiento` INT NOT NULL,
  PRIMARY KEY (`idAvion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vuelos`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos`.`ciudad` (
  `idCiudad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `aeropueto` VARCHAR(25) NOT NULL,
  `estado` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idCiudad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vuelos`.`vuelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos`.`vuelo` (
  `idVuelo` INT NOT NULL AUTO_INCREMENT,
  `fecha_salida` DATE NULL DEFAULT '0000-00-00',
  `fecha_llegada` DATE NULL DEFAULT '0000-00-00',
  `puerta_abordar` INT NOT NULL,
  `idAvion` INT NOT NULL,
  PRIMARY KEY (`idVuelo`),
  INDEX `fk_avivue` (`idAvion` ASC) VISIBLE,
  CONSTRAINT `fk_avivue`
    FOREIGN KEY (`idAvion`)
    REFERENCES `vuelos`.`avion` (`idAvion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vuelos`.`detalle_vuelo_ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos`.`detalle_vuelo_ciudad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_vuel` INT NOT NULL,
  `fk_ciu` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ciu_idx` (`fk_ciu` ASC) VISIBLE,
  INDEX `fk_vue_idx` (`fk_vuel` ASC) VISIBLE,
  CONSTRAINT `fk_ciu`
    FOREIGN KEY (`fk_ciu`)
    REFERENCES `vuelos`.`ciudad` (`idCiudad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_vuel`
    FOREIGN KEY (`fk_vuel`)
    REFERENCES `vuelos`.`vuelo` (`idVuelo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vuelos`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos`.`persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(25) NOT NULL,
  `edad` INT NOT NULL,
  `direccion` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vuelos`.`detalle_vuelo_persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos`.`detalle_vuelo_persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idVuelo` INT NOT NULL,
  `idPersona` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_per_idx` (`idPersona` ASC) VISIBLE,
  INDEX `fk_vue_idx` (`idVuelo` ASC) VISIBLE,
  CONSTRAINT `fk_per`
    FOREIGN KEY (`idPersona`)
    REFERENCES `vuelos`.`persona` (`idPersona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_vue`
    FOREIGN KEY (`idVuelo`)
    REFERENCES `vuelos`.`vuelo` (`idVuelo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vuelos`.`equipaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos`.`equipaje` (
  `idEquipaje` INT NOT NULL AUTO_INCREMENT,
  `numero_maletas` INT NOT NULL,
  `peso` DECIMAL(4,2) NOT NULL,
  `idPersona` INT NOT NULL,
  PRIMARY KEY (`idEquipaje`),
  INDEX `fk_perequi` (`idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_perequi`
    FOREIGN KEY (`idPersona`)
    REFERENCES `vuelos`.`persona` (`idPersona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
